version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sparkotto
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: sparkotto-back-backend
    build:
      context: .
      args:
        - NODE_ENV=production
        - DATABASE_URL=postgresql://postgres:postgres@db:5432/sparkotto
    pull_policy: build
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sparkotto
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: