version: "3.8"

services:
  backend:
    image: sparkotto-back:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sparkotto
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sparkotto
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data: