name: CI CD Pipeline with Jest, SonarCloud & Trivy

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Jest Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests with Jest
        run: npm test -- --ci --coverage

  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SonarCloud scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.organization=sparkotto \
            -Dsonar.projectKey=SparkOtto_sparkotto-back \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

  security:
    name: Run Trivy Security Scan
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          exit-code: "0"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      - name: Run File System Scan
        run: trivy fs --exit-code 1 --severity CRITICAL,HIGH .

  deploy:
    name: Deploy on Portainer
    runs-on: ubuntu-latest
    needs: [test, sonar, security]
    steps:
      - name: Trigger Portainer Stack webhook
        run: |
          curl -X POST "https://195.15.222.167:9443/api/stacks/webhooks/${{ secrets.TOKEN_GIT }}" --insecure